# Generated by Django 4.2.11 on 2024-07-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=100)),
                ('merchant_location', models.CharField(max_length=100)),
                ('new_code', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=100)),
                ('before_photo', models.ImageField(upload_to='before_photos/')),
                ('after_photo', models.ImageField(upload_to='after_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
